package com.mls.logistics.service;

import com.mls.logistics.domain.Movement;
import com.mls.logistics.domain.Stock;
import com.mls.logistics.dto.request.CreateMovementRequest;
import com.mls.logistics.dto.request.UpdateMovementRequest;
import com.mls.logistics.exception.ResourceNotFoundException;
import com.mls.logistics.repository.MovementRepository;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * Service layer for Movement-related business operations.
 * 
 * This class acts as an intermediary between controllers and repositories,
 * enforcing business rules and application logic.
 */
@Service
@Transactional(readOnly = true)
public class MovementService {

    private final MovementRepository movementRepository;

    /**
     * Constructor-based dependency injection.
     * This is the recommended approach in Spring.
     */
    public MovementService(MovementRepository movementRepository) {
        this.movementRepository = movementRepository;
    }

    /**
     * Retrieves all registered movements.
     */
    public List<Movement> getAllMovements() {
        return movementRepository.findAll();
    }

    /**
     * Retrieves all registered movements with ordering.
     */
    public List<Movement> getAllMovements(Sort sort) {
        return movementRepository.findAll(sort);
    }

    /**
     * Retrieves a movement by its identifier.
     */
    public Optional<Movement> getMovementById(Long id) {
        return movementRepository.findById(id);
    }

    /**
     * Creates a new movement.
     * 
     * Business rules can be added here in the future
     * (e.g. validation of movement types).
     */
    @Transactional
    public Movement createMovement(Movement movement) {
        return movementRepository.save(movement);
    }

    /**
     * Creates a manual movement record.
     *
     * NOTE: Movements generated by stock adjustments are created automatically
     * by StockService.adjustStock() and StockService.createStock().
     * This method is reserved for manual audit corrections only.
     *
     * @param request DTO containing movement data
     * @return created movement entity
     */
    @Transactional
    public Movement createMovement(CreateMovementRequest request) {
        Movement movement = new Movement();

        Stock stock = new Stock();
        stock.setId(request.getStockId());

        movement.setStock(stock);
        movement.setType(request.getType());
        movement.setQuantity(request.getQuantity());
        movement.setDateTime(request.getDateTime());

        return movementRepository.save(movement);
    }

    /**
     * Updates an existing movement.
     * 
     * Only non-null fields from the request are updated.
     *
     * @param id movement identifier
     * @param request update data
     * @return updated movement
     * @throws ResourceNotFoundException if movement doesn't exist
     */
    @Transactional
    public Movement updateMovement(Long id, UpdateMovementRequest request) {
        Movement movement = movementRepository
                .findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Movement", "id", id));

        if (request.getStockId() != null) {
            Stock stock = new Stock();
            stock.setId(request.getStockId());
            movement.setStock(stock);
        }
        if (request.getType() != null) {
            movement.setType(request.getType());
        }
        if (request.getQuantity() != null) {
            movement.setQuantity(request.getQuantity());
        }
        if (request.getDateTime() != null) {
            movement.setDateTime(request.getDateTime());
        }

        return movementRepository.save(movement);
    }

    /**
     * Deletes a movement by ID.
     *
     * @param id movement identifier
     * @throws ResourceNotFoundException if movement doesn't exist
     */
    @Transactional
    public void deleteMovement(Long id) {
        if (!movementRepository.existsById(id)) {
            throw new ResourceNotFoundException("Movement", "id", id);
        }
        movementRepository.deleteById(id);
    }
}
